name = input("Enter your name: ")
email = input("Enter your email: ")
slack = input("Enter your slack username: ")
biostack= input("Enter your biostack: ")
print ( "Hello, my name is "+ name+"," " my email is "+ email+"," + "@" +slack + " is my slack username," +" and I choosed "+ biostack +" as my biostack!")
