# -*- coding: utf-8 -*-
"""Tiwa.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1noqxn74asbMOImYH50g4u8-2qew2Io7H
"""

Print ('Name: Aina Tiwalola Jadesola')

Print ('Email: tiwalolajaina@gmail.com')

Print ('Slack username: Tiwalola')

Print ('Biostack: Genomics')